accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_create'),
    path('posts/<int:post_id>/comments/', views.get_post_comments, name='get_post_comments'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('comments/unapproved/', views.un_comments, name='unapproved_comments'),
    path('comments/<int:comment_id>/approve/', views.approve_comment, name='approve_comment'),
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

main/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to='post_images', null=True, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.author}:{self.post}'

blog/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth import get_user_model
from django.forms import ModelForm

User = get_user_model()


class PostForm(ModelForm):
    created_date = forms.DateTimeField(
        input_formats=['%Y-%m-%d %H:%M:%S'],
        widget=forms.DateTimeInput(
            attrs={'class': 'form-control', 'type': 'datetime-local'}
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'created_date', 'image']


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='Comment',
        widget=forms.Textarea(attrs={
            'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                     ' focus:outline-none focus:ring focus:ring-blue-500',
            'rows': '4',
            'required': True,
        })
    )
    author = forms.ModelChoiceField(
        label='Author',
        queryset=User.objects.all(),
        widget=forms.Select(attrs={
            'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                     ' focus:outline-none focus:ring focus:ring-blue-500',
            'required': True,
        })
    )

    class Meta:
        model = Comment
        fields = ['author', 'content']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth import get_user_model
from .models import Post, Comment
from django.db.models import Count, Q
from django import forms
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.admin.views.decorators import staff_member_required

User = get_user_model()


@staff_member_required
def un_comments(request):
    unapproved_comments = Comment.objects.filter(is_approved=False)
    return render(request, 'blog/unapproved_comments.html', {
        'comments': unapproved_comments
    })


@staff_member_required
def approve_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.is_approved = True
    comment.save()
    return redirect('blog:unapproved_comments')


@staff_member_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('blog:unapproved_comments')


class PostListView(View):
    def get(self, request):
        posts = Post.objects.annotate(
            approved_comment_count=Count('comments',
                                         filter=Q(comments__is_approved=True))
                                      ).order_by('-created_date')
        return render(request, 'blog/post_list.html', {'posts': posts})


class CreatePostView(LoginRequiredMixin, UserPassesTestMixin, View):

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request):
        form = self.PostForm()
        return render(request, 'blog/post_form.html', {'form': form})

    def post(self, request):
        form = self.PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:post_list')
        return render(request, 'blog:post_form.html', {'form': form})

    class PostForm(forms.ModelForm):
        has_code_block = forms.BooleanField(required=False, label="Содержит компьютерный код")

        title = forms.CharField(
            label='Title',
            widget=forms.TextInput(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'required': True,
            })
        )
        content = forms.CharField(
            label='Content',
            widget=forms.Textarea(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'rows': '4',
                'required': True,
            })
        )
        author = forms.ModelChoiceField(
            label='Author',
            queryset=User.objects.all(),
            widget=forms.Select(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'required': True,
            })
        )
        created_date = forms.DateTimeField(
            label='Created Date',
            input_formats=['%Y-%m-%d %H:%M:%S'],
            widget=forms.DateTimeInput(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'type': 'datetime-local',
                'required': True,
            })
        )
        image = forms.ImageField(
            label='Image',
            required=False,
            widget=forms.FileInput(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
            })
        )

        class Meta:
            model = Post
            fields = ['title', 'content', 'author', 'created_date', 'image', 'has_code_block']


class PostDetailView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        approve_comments = post.comments.filter(is_approved=True)
        return render(request, 'blog/post_detail.html', {
            'post': post,
            'comment_form': self.CommentForm(),
            'comments': approve_comments,
        })

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = self.CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect('blog:post_detail', pk=post.pk)
        comments = post.comments.filter(is_approved=True)
        return render(request, 'blog/post_detail.html', {
            'post': post,
            'comment_form': comment_form,
            'comments': comments,
        })

    class CommentForm(forms.ModelForm):
        content = forms.CharField(
            label='Comment',
            widget=forms.Textarea(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'rows': '4',
                'required': True,
            })
        )
        author = forms.ModelChoiceField(
            label='Author',
            queryset=User.objects.all(),
            widget=forms.Select(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'required': True,
            })
        )

        class Meta:
            model = Comment
            fields = ['author', 'content']


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, View):
    model = Post
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:post_list')

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['pk'])

    def get(self, request, pk):
        post = self.get_object()
        form = self.PostForm(instance=post)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        post = self.get_object()
        form = self.PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

    def test_func(self):
        post = self.get_object()
        return self.request.user.is_staff or post.author == self.request.user

    class PostForm(forms.ModelForm):
        title = forms.CharField(
            label='Title',
            widget=forms.TextInput(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'required': True,
            })
        )
        content = forms.CharField(
            label='Content',
            widget=forms.Textarea(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
                'rows': '4',
                'required': True,
            })
        )
        image = forms.ImageField(
            label='Image',
            required=False,
            widget=forms.FileInput(attrs={
                'class': 'bg-gray-100 border border-gray-300 rounded-lg py-2 px-4 block w-full'
                         ' focus:outline-none focus:ring focus:ring-blue-500',
            })
        )

        class Meta:
            model = Post
            fields = ['title', 'content', 'image']


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, View):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_list')

    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['pk'])

    def get(self, request, pk):
        post = self.get_object()
        return render(request, self.template_name, {'object': post})

    def post(self, request, pk):
        post = self.get_object()
        post.delete()
        return redirect(self.success_url)

    def test_func(self):
        post = self.get_object()
        return self.request.user.is_staff or post.author == self.request.user


def get_post_comments(request, post_id):
    try:
        comments = Comment.objects.filter(post_id=post_id).values('author', 'content')
        return JsonResponse(list(comments), safe=False)
    except Exception as e:
        print(f'Error fetching comments: {e}')
        return JsonResponse({'error': 'Error fetching comments'}, status=500)

templates/blog/comment_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-white rounded-lg shadow-md p-6">
        <h1 class="text-3xl font-bold mb-4">Add Comment</h1>
        <form method="post" action="{% url 'blog:comment_create' post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Submit</button>
        </form>
    </div>
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-2xl font-bold mb-4">Delete Post</h1>
    <p class="mb-4">Are you sure you want to delete the post "{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <div class="flex justify-end">
            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mr-2">
                Delete
            </button>
            <a href="{% url 'blog:post_detail' object.pk %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-white rounded-lg shadow-md p-8">
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="max-w-full h-auto mb-4">
        {% endif %}
        <h1 class="text-3xl font-bold mb-4">{{ post.title }}</h1>
        <div class="flex justify-between items-center text-gray-500 mb-4">
            <p>Author: {{ post.author }}</p>
            <p>Published: {{ post.created_date }}</p>
        </div>
            <p class="text-lg mb-8">{{ post.content }}</p>
        <div class="flex justify-end">
            {% if user.is_staff or user == post.author %}
                <a href="{% url 'blog:post_update' post.pk %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mr-2">
                    Edit
                </a>
                <a href="{% url 'blog:post_delete' post.pk %}" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                    Delete
                </a>
            {% endif %}
        </div>
        <h2 class="text-2xl font-bold mb-4">Comments</h2>
        {% if comments %}
            <div class="space-y-4">
                {% for comment in comments %}
                    <div class="bg-gray-100 rounded-lg p-4">
                        <p class="text-gray-500 mb-2">{{ comment.author }} - {{ comment.created_date }}</p>
                        <p>{{ comment.content }}</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No comments yet.</p>
        {% endif %}

        <h2 class="text-2xl font-bold mt-8 mb-4">Add Comment</h2>
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'blog:post_detail' post.id %}" class="space-y-4">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Submit
    </button>
</form>
    </div>
{% else %}
<p>Зарегистрируйтесь или авторизуйтесь, чтобы комментировать!</p>

<a href="{% url 'accounts:register' %}" class="hover:bg-blue-700">Register </a>|
<a href="{% url 'accounts:login' %}" class="hover:bg-blue-700"> Login</a>
{% endif %}
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-white rounded-lg shadow-md p-8">
        <h1 class="text-3xl font-bold mb-4">{% if form.instance.pk %}Edit Post{% else %}Create Post{% endif %}</h1>
        <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}" class="block text-gray-700 font-bold mb-2">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <p class="text-red-500 text-xs italic">{{ field.errors|first }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Save
            </button>
        </form>
    </div>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-3xl font-bold mb-4">All Posts</h1>

    {% if posts %}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for post in posts %}
                <div class="bg-white rounded-lg shadow-md p-4 flex flex-col justify-between">
                    <div>
                        <div class="flex justify-between items-center mb-2">
                            <p class="text-gray-500 text-sm"><i class="fas fa-calendar-alt"></i> {{ post.created_date }}</p>
                            <p class="text-gray-500 text-sm"><i class="fas fa-comment comment-icon" data-post-id="{{ post.id }}"></i> {{ post.approved_comment_count }}</p>


                        </div>
                        <h2 class="text-xl font-bold mb-2">{{ post.title }}</h2>
                        <p class="text-gray-600 mb-4">{{ post.content|truncatewords:20 }}</p>
                        <p class="text-gray-500 text-sm"><i class="fas fa-pen"></i> {{ post.author }}</p>
                    </div>
                    <div class="flex justify-between items-center mt-4">
                        <a href="{% url 'blog:post_detail' post.id %}" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Read More</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No posts available.</p>
    {% endif %}
{% endblock %}

templates/blog/unapproved_comments.html
{% extends 'base.html' %}

{% block content %}
    <div class="bg-white rounded-lg shadow-md p-8">
        <h1 class="text-3xl font-bold mb-4">Unapproved Comments</h1>

        {% if comments %}
            <div class="space-y-4">
                {% for comment in comments %}
                    <div class="bg-gray-100 rounded-lg p-4">
                        <p class="text-gray-500 mb-2">{{ comment.author }} - {{ comment.created_at }}</p>
                        <p>{{ comment.content }}</p>
                        <div class="flex justify-end mt-4">
                            <a href="{% url 'blog:approve_comment' comment.id %}" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded mr-2">
                                Approve
                            </a>
                            <a href="{% url 'blog:delete_comment' comment.id %}" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                                Delete
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No unapproved comments.</p>
        {% endif %}
    </div>
{% endblock %}